manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: dhruvinsh
      url-base: https://github.com/dhruvinsh
    - name: urob
      url-base: https://github.com/urob
    - name: AngryPancake
      url-base: https://github.com/AngryPancake
  projects:
    # - name: zmk
    #   remote: AngryPancake
    #   revision: disable-usb-sof
    #   import: app/west.yml
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-tri-state
      remote: dhruvinsh
      revision: main
    - name: zmk-behavior-tda
      remote: AngryPancake
      revision: main
    - name: zmk-behavior-send-string
      remote: AngryPancake
      revision: main
  self:
    path: config